spring:
  application:
    name : order-service
  # Uncomment the following lines to enable H2 console and JPA settings
  # h2:
  #   console:
  #     enabled: true
  # datasource:
  #   url: jdbc:h2:mem:test
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8082


